name: github action context variable

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "context"
        env: 
         COMMIT_ID: ${{ github.sha }}
        run: echo "Commit id:$COMMIT_ID"
          
      - name: print github context 
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          
          GITHUB_EVENT_COMMITS_AUTHOR_NAME: ${{ github.event.commits.author.name }}
          GITHUB_EVENT_COMMITS_AUTHOR_USERNAME: ${{ github.event.commits.author.username }}
          
          GITHUB_EVENT_REPOSITORY_LABELS_URL: ${{ github.event.repository.labels_url }}
          GITHUB_EVENT_REPOSITORY_OWNER: ${{ toJson(github.event.repository.owner) }}
          
        run: |
          echo "github.acitor: $GITHUB_ACTOR"
          
          echo "github.event.commits.author.name: $GITHUB_EVENT_COMMITS_AUTHOR_NAME"
          echo "github.event.commits.author.username: $GITHUB_EVENT_COMMITS_AUTHOR_USERNAME"
          
          echo "github.event.repository.lables_url: $GITHUB_EVENT_REPOSITORY_LABELS_URL"
          echo "github.event.repository.owner: $GITHUB_EVENT_REPOSITORY_OWNER"
          
        
        
